<?php

namespace SRAG\Plugins\Hub2\Object\Session;

use SRAG\Plugins\Hub2\Object\ARMetadataAwareObject;

/**
 * Class ARSession
 *
 * @author Fabian Schmid <fs@studer-raimann.ch>
 */
class ARSession extends ARMetadataAwareObject implements ISession {

	/**
	 * @inheritdoc
	 */
	public static function returnDbTableName() {
		return 'sr_hub2_session';
	}


	/**
	 * @inheritDoc
	 */
	public function update() {
		parent::update(); // TODO: Change the autogenerated stub
	}
}